#!/usr/bin/env ruby
puts <<EOS
                                      ..,ONMMMMMO.
                                      NM8~:~:.,+NMM=
                                     MO          .MM:
                                    NM.           ,MN
  ..                              .7MN         . . 8M,
==. ?N:                           .MMN .,,..  8$ZZ.~MN
.$.    N8    ,DD.                 ,MMN ...+:.      .MMM
  D      8D.Z=  .$.               NMMM..,~8I  ,88+. MMMM:.
   ,~...  ,MM   .N .              MMMM7.       .... MMMMM,
 DZ.. .:OZ.:M. ..8=              .MMMM.            .OMMMMM
 :7 .      8+$M:.D+              +MMMM,  .:N+,MMD:  7MMMMM.
 .MM7:.... 8    .M.              7MMMMM. MMMMZMMMMO.7MMMMM.
,?.  ..  ..8    ,M               =MMMMM MMN8$7O8DMM.OMMM~ +.
 N..   .  .+    M,               .MMMMMOM M8. .OM.MIMMMZ  =,.
 =NZI+~,  +    I8                .MMMMMMM= .=DD,  MMMMMI  ~~
 O.      .N   + M.              IMMMMMMMMMD ~MN 7MMMMMMM  .Z
 .MNZZNMZ.    . MM             7MMMMMMMMMMMMMMMMMMMMMMMM, .~M,.
    ID=. .  .   MMI            MMMMMMMMMMMMMMMMMMMMMMMMMD.    .+N
   .DMO,ZND+.   MMM.          :MMMMMMMMN =MMMMMMMMN:ZMMM,.    +M~,$OD$
   .MMO...      MMM           OMMMMMMMM~ . ,I++O7.  OMMM= .IM7 . .=..+MNI.
   .8MO        :MMM         .MMMMMMMMMM.            MMMMM=       ~D   ?MO:7MN...
   +$ON.       $NMM        .NMMMMMMMMM7.           .MMMMM.   .8Z.      :7N...MM:
   O7?N        M+MMNMMMMMMMMMMMMMMMMMN              MMMMMM8D. .   $,  .$8 M  ..,$MN~,,.
   N$:=M.    .NM.MM.           ?MMMMMMO. ..         D IO$IM:D.,$O, ,.  O.I,Z       :M:  .+MI
   MO, MMI ..NM8.MM. =.            MM..IMN7,.  .,IDN7~MMMMMM,      N  .Z N.M.       ,M.     =N.
  .MO. MMMMMMMM::MM  .:             .    .M :+I?=D.~.MMMMMMM?,,~INMMNNM+ ~ ~.        D8.     ,8.
  .M8. MMMMMMMM ZM$.  8                   7.     ~ M,MM+MMMMMMMMMMMMMMM.. , :        ,M.     .O+
  .MO. MMMMMMMI.MM,   N                    = .....,IDI. MMMMMMMM8MMMMMM.. =           M+      .M.
  .MZ~.MMMMMMM..MM .  N     .=.              ?M,NMMMMMM?~MM$IMMM7MMMMM7               :O       M
   M7I.NMMMMM8.$MZ.~  8     .~,          : MMMMMMMMMMMMM.~OOIMMM+MMMMM,               .N       M
   N=D OMMMMM, MM  O .I      .7.      MMMMMMMMMMMMMMMMMMMMMD7NMM:MMMMN                 D      .M
   O:M,~MMMMD NM?  D.=,       8       OMMMMMMMMMMMMMMMMMMMMMZZMM?MMMM: ...             Z      .M
   +=M$ MMMZ :MN  ~, D.       I.      ~MMMMMMM+,,~I,  .NMMMMMZ.MDNMM7   I.             .      .M.
   .$NM .,.. MM  .M :N.       :~      .MMMMMM.          MMMMMMZ=M,MM.  .M.                    7M
   .N.MM~  $MZ.  O. N?         N.    ,MMMMMMM.          MMMMMMMM+8Z:   NZ.            .      .MI.
   .M.=MMMMN.. .+=..M.         M.    NMMMMMMMD         8MMMMMMM.MMM.  $M. .           ?,     ~M.
    +. ~MM ..  $,  M:          N:    . 7MMMMMMN      .~MMMMMM8,MMMMMMMMMMM         ..M.     :MM
     D   N . ,M N NN.          I8.      $MMMMMMM?.. .?MMMMMMM?OMMMMMMMMMMMMMMMMMMMMI   . ...MM$
     7?   .?N.7O DM            ,M      ZMMMMMMMMMM7.IMMMMMMMMD$MMMMMMMMMMMMMMMMMMMMMMMMZ: IMMN.
     .~MM?.=NM~DM8..            M        8MMMMMMMMMMMMMMMMM7=MMMMMMMMMMMMMMMMMD.IMMMNZZNMMN~
EOS
